"""add_supplier_payments_customer_receipts

Revision ID: feeee5ac8d0f
Revises: 2af82f82cdc2
Create Date: 2026-04-25 20:11:30.539466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feeee5ac8d0f'
down_revision: Union[str, None] = '2af82f82cdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('is_advance', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['crm_purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('dealer_id', sa.UUID(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('dealer_order_id', sa.UUID(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['dealer_order_id'], ['dealer_orders.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_receipts')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
