"""initial_baseline

Revision ID: ba22dd09a6a3
Revises: 
Create Date: 2026-03-31 16:00:36.193393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba22dd09a6a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allowed_transitions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('allowed_transitions', 'from_stage',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('allowed_transitions', 'to_stage',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('allowed_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('allowed_transitions_from_stage_to_stage_key'), 'allowed_transitions', type_='unique')
    op.drop_index(op.f('ix_allowed_trans_from'), table_name='allowed_transitions')
    op.create_unique_constraint('uq_transition', 'allowed_transitions', ['from_stage', 'to_stage'])
    op.alter_column('attendance', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audit_logs', 'username',
               existing_type=sa.VARCHAR(length=80),
               server_default=None,
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'table_name',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'record_id',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.alter_column('audit_scan_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audit_scan_items', 'scanned_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('idx_asi_audit_id'), table_name='audit_scan_items')
    op.alter_column('dealer_assignments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dealer_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_calls', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dealer_calls', 'call_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_calls', 'call_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_calls', 'call_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_calls', 'whatsapp_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_orders', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dealer_orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_orders', 'paid_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_orders', 'due_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_orders', 'invoice_sent_whatsapp',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_orders', 'payment_reminder_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealer_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dealers', 'dealer_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealers', 'credit_limit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealers', 'outstanding_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealers', 'total_purchases',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dealers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('dealers_dealer_code_key'), 'dealers', type_='unique')
    op.create_index(op.f('ix_dealers_dealer_code'), 'dealers', ['dealer_code'], unique=True)
    op.alter_column('device_aging', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_aging', 'days_in_stage',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('device_aging', 'total_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('device_aging', 'is_stuck',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('device_aging', 'is_dead_stock',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('device_aging', 'refreshed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('device_aging_device_id_key'), 'device_aging', type_='unique')
    op.create_index(op.f('ix_device_aging_device_id'), 'device_aging', ['device_id'], unique=True)
    op.alter_column('device_costing', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_costing', 'base_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('device_costing', 'parts_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('device_costing', 'labour_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('device_costing', 'total_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('device_costing', 'expected_sale_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('device_costing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('device_costing_device_id_key'), 'device_costing', type_='unique')
    op.create_index(op.f('ix_device_costing_device_id'), 'device_costing', ['device_id'], unique=True)
    op.alter_column('device_location_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_location_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('idx_dll_device_id'), table_name='device_location_logs')
    op.drop_index(op.f('idx_dll_location_id'), table_name='device_location_logs')
    op.drop_index(op.f('idx_dll_logged_at'), table_name='device_location_logs')
    op.create_index(op.f('ix_device_location_logs_logged_at'), 'device_location_logs', ['logged_at'], unique=False)
    op.alter_column('devices', 'storage_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('devices', 'bios_password',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('devices', 'floor',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('devices_lot_line_item_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'lot_line_items', ['lot_line_item_id'], ['id'])
    op.alter_column('inventory_audits', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inventory_audits', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', name='auditstatus'),
               server_default=None,
               nullable=True)
    op.alter_column('inventory_audits', 'initiated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('inventory_audits', 'expected_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('inventory_audits', 'found_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('inventory_audits', 'missing_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('inventory_audits', 'extra_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('iqc_inspections', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('iqc_inspections', 'inspected_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_iqc_inspections_device_id'), table_name='iqc_inspections')
    op.alter_column('lot_line_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lot_line_items', 'has_ram',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('lot_line_items', 'has_storage',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('lot_line_items', 'qty',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lot_line_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_lot_line_items_lot_id'), table_name='lot_line_items')
    op.create_index(op.f('ix_lot_line_items_lot_id'), 'lot_line_items', ['lot_id'], unique=False)
    op.drop_constraint(op.f('lot_line_items_lot_id_fkey'), 'lot_line_items', type_='foreignkey')
    op.create_foreign_key(None, 'lot_line_items', 'lots', ['lot_id'], ['id'])
    op.alter_column('lots', 'supplier_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('lots', 'invoice_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('market_availability', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_availability', 'trade_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_availability', 'is_negotiable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('market_availability', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('market_availability', 'posted_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('market_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('market_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_market_active'), table_name='market_availability')
    op.drop_index(op.f('ix_market_brand'), table_name='market_availability')
    op.drop_index(op.f('ix_market_dealer'), table_name='market_availability')
    op.drop_index(op.f('ix_market_model'), table_name='market_availability')
    op.drop_index(op.f('ix_market_trade'), table_name='market_availability')
    op.alter_column('master_data', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('master_data', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('master_data', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('master_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('qc_checks', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_qc_checks_device_id'), 'qc_checks', ['device_id'], unique=False)
    op.alter_column('repair_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repair_attempts', 'attempt_no',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repair_attempts', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               nullable=False)
    op.alter_column('repair_attempts', 'outcome',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('repair_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_repair_attempts_device'), table_name='repair_attempts')
    op.create_index(op.f('ix_repair_attempts_device_id'), 'repair_attempts', ['device_id'], unique=False)
    op.alter_column('returns', 'action_taken',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('returns', 'reentered_stage',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('spare_parts_ledger', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('spare_parts_ledger', 'entry_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('spare_parts_ledger', 'cost_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               nullable=False)
    op.alter_column('spare_parts_ledger', 'total_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('spare_parts_ledger', 'reference_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('spare_parts_ledger', 'reference_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('spare_parts_ledger', 'created_by',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('spare_parts_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_spl_device_id'), table_name='spare_parts_ledger')
    op.drop_index(op.f('ix_spl_part_id'), table_name='spare_parts_ledger')
    op.create_index(op.f('ix_spare_parts_ledger_part_id'), 'spare_parts_ledger', ['part_id'], unique=False)
    op.alter_column('stage_master', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stage_master', 'name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('stage_master', 'label',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('stage_master', 'sequence',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stage_master', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('stage_master', 'is_active')
    op.alter_column('stock_transfers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_transfers', 'transfer_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_transfers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_stock_transfers_transfer_date'), table_name='stock_transfers')
    op.alter_column('storage_locations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('storage_locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('storage_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('telecalling_records', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('telecalling_records', 'call_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_records', 'whatsapp_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('telecalling_sessions', 'session_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'total_calls',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'connected_calls',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'interested_leads',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'orders_placed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'target_calls',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_permissions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_permissions', 'granted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_permissions', 'granted_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.alter_column('whatsapp_broadcasts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('whatsapp_broadcasts', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'total_recipients',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'sent_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'failed_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_groups', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('whatsapp_groups', 'participant_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_groups', 'group_category',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_groups', 'last_synced',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('whatsapp_messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'direction',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('whatsapp_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('whatsapp_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'disconnected'::character varying"),
               existing_nullable=True)
    op.alter_column('whatsapp_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('whatsapp_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'direction',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'outgoing'::character varying"),
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('whatsapp_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('whatsapp_groups', 'last_synced',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('whatsapp_groups', 'group_category',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'other'::character varying"),
               existing_nullable=True)
    op.alter_column('whatsapp_groups', 'participant_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('whatsapp_groups', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('whatsapp_broadcasts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'done'::character varying"),
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'failed_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'sent_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'total_recipients',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=True)
    op.alter_column('whatsapp_broadcasts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.alter_column('user_permissions', 'granted_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('user_permissions', 'granted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user_permissions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('telecalling_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'target_calls',
               existing_type=sa.INTEGER(),
               server_default=sa.text('50'),
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'orders_placed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'interested_leads',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'connected_calls',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'total_calls',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'session_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telecalling_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('telecalling_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telecalling_records', 'whatsapp_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('telecalling_records', 'call_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telecalling_records', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('storage_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('storage_locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('storage_locations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_transfers_transfer_date'), 'stock_transfers', [sa.literal_column('transfer_date DESC')], unique=False)
    op.alter_column('stock_transfers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('stock_transfers', 'transfer_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('stage_master', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.alter_column('stage_master', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('stage_master', 'sequence',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('stage_master', 'label',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('stage_master', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('stage_master', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_spare_parts_ledger_part_id'), table_name='spare_parts_ledger')
    op.create_index(op.f('ix_spl_part_id'), 'spare_parts_ledger', ['part_id'], unique=False)
    op.create_index(op.f('ix_spl_device_id'), 'spare_parts_ledger', ['device_id'], unique=False)
    op.alter_column('spare_parts_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('spare_parts_ledger', 'created_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('spare_parts_ledger', 'reference_id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('spare_parts_ledger', 'reference_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('spare_parts_ledger', 'total_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('spare_parts_ledger', 'cost_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('spare_parts_ledger', 'entry_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('spare_parts_ledger', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('returns', 'reentered_stage',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('returns', 'action_taken',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_repair_attempts_device_id'), table_name='repair_attempts')
    op.create_index(op.f('ix_repair_attempts_device'), 'repair_attempts', ['device_id'], unique=False)
    op.alter_column('repair_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('repair_attempts', 'outcome',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('repair_attempts', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('repair_attempts', 'attempt_no',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('repair_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_qc_checks_device_id'), table_name='qc_checks')
    op.alter_column('qc_checks', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('master_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('master_data', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('master_data', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('master_data', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('ix_market_trade'), 'market_availability', ['trade_type'], unique=False)
    op.create_index(op.f('ix_market_model'), 'market_availability', ['model'], unique=False)
    op.create_index(op.f('ix_market_dealer'), 'market_availability', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_market_brand'), 'market_availability', ['brand'], unique=False)
    op.create_index(op.f('ix_market_active'), 'market_availability', ['is_active'], unique=False)
    op.alter_column('market_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('market_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('market_availability', 'posted_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('market_availability', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('market_availability', 'is_negotiable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('market_availability', 'trade_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'sell'::character varying"),
               existing_nullable=False)
    op.alter_column('market_availability', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('lots', 'invoice_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('lots', 'supplier_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'lot_line_items', type_='foreignkey')
    op.create_foreign_key(op.f('lot_line_items_lot_id_fkey'), 'lot_line_items', 'lots', ['lot_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lot_line_items_lot_id'), table_name='lot_line_items')
    op.create_index(op.f('idx_lot_line_items_lot_id'), 'lot_line_items', ['lot_id'], unique=False)
    op.alter_column('lot_line_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('lot_line_items', 'qty',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('lot_line_items', 'has_storage',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('lot_line_items', 'has_ram',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('lot_line_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('ix_iqc_inspections_device_id'), 'iqc_inspections', ['device_id'], unique=False)
    op.alter_column('iqc_inspections', 'inspected_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('iqc_inspections', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('inventory_audits', 'extra_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('inventory_audits', 'missing_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('inventory_audits', 'found_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('inventory_audits', 'expected_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('inventory_audits', 'initiated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('inventory_audits', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', name='auditstatus'),
               server_default=sa.text("'pending'::auditstatus"),
               nullable=False)
    op.alter_column('inventory_audits', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_lot_line_item_id_fkey'), 'devices', 'lot_line_items', ['lot_line_item_id'], ['id'], ondelete='SET NULL')
    op.alter_column('devices', 'floor',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('devices', 'bios_password',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('devices', 'storage_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_index(op.f('ix_device_location_logs_logged_at'), table_name='device_location_logs')
    op.create_index(op.f('idx_dll_logged_at'), 'device_location_logs', ['logged_at'], unique=False)
    op.create_index(op.f('idx_dll_location_id'), 'device_location_logs', ['location_id'], unique=False)
    op.create_index(op.f('idx_dll_device_id'), 'device_location_logs', ['device_id'], unique=False)
    op.alter_column('device_location_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('device_location_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_device_costing_device_id'), table_name='device_costing')
    op.create_unique_constraint(op.f('device_costing_device_id_key'), 'device_costing', ['device_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('device_costing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('device_costing', 'expected_sale_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('device_costing', 'total_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('device_costing', 'labour_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('device_costing', 'parts_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('device_costing', 'base_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('device_costing', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_device_aging_device_id'), table_name='device_aging')
    op.create_unique_constraint(op.f('device_aging_device_id_key'), 'device_aging', ['device_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('device_aging', 'refreshed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('device_aging', 'is_dead_stock',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('device_aging', 'is_stuck',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('device_aging', 'total_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('device_aging', 'days_in_stage',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('device_aging', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_dealers_dealer_code'), table_name='dealers')
    op.create_unique_constraint(op.f('dealers_dealer_code_key'), 'dealers', ['dealer_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('dealers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dealers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dealers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.alter_column('dealers', 'total_purchases',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('dealers', 'outstanding_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('dealers', 'credit_limit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('dealers', 'dealer_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'retail'::character varying"),
               existing_nullable=True)
    op.alter_column('dealers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('dealer_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dealer_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('dealer_orders', 'payment_reminder_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('dealer_orders', 'invoice_sent_whatsapp',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('dealer_orders', 'due_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('dealer_orders', 'paid_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('dealer_orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('dealer_orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dealer_orders', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('dealer_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dealer_calls', 'whatsapp_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('dealer_calls', 'call_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'phone'::character varying"),
               existing_nullable=True)
    op.alter_column('dealer_calls', 'call_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'outbound'::character varying"),
               existing_nullable=True)
    op.alter_column('dealer_calls', 'call_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dealer_calls', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('dealer_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('dealer_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('dealer_assignments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_asi_audit_id'), 'audit_scan_items', ['audit_id'], unique=False)
    op.alter_column('audit_scan_items', 'scanned_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('audit_scan_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_record'), 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'record_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('audit_logs', 'table_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('audit_logs', 'username',
               existing_type=sa.String(length=50),
               server_default=sa.text("'system'::character varying"),
               type_=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'present'::character varying"),
               existing_nullable=True)
    op.alter_column('attendance', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint('uq_transition', 'allowed_transitions', type_='unique')
    op.create_index(op.f('ix_allowed_trans_from'), 'allowed_transitions', ['from_stage'], unique=False)
    op.create_unique_constraint(op.f('allowed_transitions_from_stage_to_stage_key'), 'allowed_transitions', ['from_stage', 'to_stage'], postgresql_nulls_not_distinct=False)
    op.alter_column('allowed_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('allowed_transitions', 'to_stage',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('allowed_transitions', 'from_stage',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('allowed_transitions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
