"""add_customer_state_to_sales

Revision ID: ea9ba80876e8
Revises: 4e2fc1624802
Create Date: 2026-04-25 19:40:13.843194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9ba80876e8'
down_revision: Union[str, None] = '4e2fc1624802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('customer_state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'customer_state')
    # ### end Alembic commands ###
