"""add_grade_price_matrix

Revision ID: 4e2fc1624802
Revises: crm_add_crm_tables
Create Date: 2026-04-25 17:47:35.803280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e2fc1624802'
down_revision: Union[str, None] = 'crm_add_crm_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_grade_price_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('material_type', sa.String(length=30), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('min_buy_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_buy_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_sell', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_grade_price_matrix_device_type'), 'crm_grade_price_matrix', ['device_type'], unique=False)
    op.drop_index(op.f('ix_sourcing_deals_account_name'), table_name='sourcing_deals')
    op.drop_index(op.f('ix_sourcing_deals_next_action'), table_name='sourcing_deals')
    op.drop_index(op.f('ix_sourcing_deals_status'), table_name='sourcing_deals')
    op.drop_table('sourcing_deals')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'details')
    op.alter_column('crm_activities', 'activity_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_activities', 'followup_done',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_crm_activities_contact_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_deal_id'), table_name='crm_activities')
    op.alter_column('crm_contacts', 'contact_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_contacts', 'credit_limit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_contacts', 'outstanding',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_contacts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_quote_items', 'line_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('crm_quote_items', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('crm_quote_items', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_quotes', 'total_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_quotes', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_sales_opportunities', 'stage',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_sales_opportunities', 'priority',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_sourcing_deals', 'stage',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_sourcing_deals', 'payment_advance_pct',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('crm_sourcing_deals', 'priority',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.drop_column('devices', 'sale_mode')
    op.drop_index(op.f('ix_iqc_inspections_device_id'), table_name='iqc_inspections')
    op.drop_column('lots', 'lot_type')
    op.alter_column('qc_checks', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('sales', 'approved_at')
    op.drop_column('sales', 'approval_status')
    op.drop_column('sales', 'sale_mode')
    op.drop_column('sales', 'approval_notes')
    op.drop_column('sales', 'approved_by')
    op.drop_column('sales', 'approval_required')
    op.drop_index(op.f('ix_stock_transfers_transfer_date'), table_name='stock_transfers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_transfers_transfer_date'), 'stock_transfers', [sa.literal_column('transfer_date DESC')], unique=False)
    op.add_column('sales', sa.Column('approval_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('approved_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('approval_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('sale_mode', sa.VARCHAR(length=30), server_default=sa.text("'refurbished'::character varying"), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('approval_status', sa.VARCHAR(length=20), server_default=sa.text("'approved'::character varying"), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('qc_checks', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.add_column('lots', sa.Column('lot_type', sa.VARCHAR(length=30), server_default=sa.text("'refurbishment'::character varying"), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_iqc_inspections_device_id'), 'iqc_inspections', ['device_id'], unique=False)
    op.add_column('devices', sa.Column('sale_mode', sa.VARCHAR(length=30), server_default=sa.text("'refurbished'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('crm_sourcing_deals', 'priority',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=True)
    op.alter_column('crm_sourcing_deals', 'payment_advance_pct',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('crm_sourcing_deals', 'stage',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'lead'::character varying"),
               existing_nullable=True)
    op.alter_column('crm_sales_opportunities', 'priority',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=True)
    op.alter_column('crm_sales_opportunities', 'stage',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'lead'::character varying"),
               existing_nullable=True)
    op.alter_column('crm_quotes', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=True)
    op.alter_column('crm_quotes', 'total_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('crm_quote_items', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('crm_quote_items', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('crm_quote_items', 'line_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('crm_contacts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.alter_column('crm_contacts', 'outstanding',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('crm_contacts', 'credit_limit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('crm_contacts', 'contact_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'supplier'::character varying"),
               existing_nullable=True)
    op.create_index(op.f('ix_crm_activities_deal_id'), 'crm_activities', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_contact_id'), 'crm_activities', ['contact_id'], unique=False)
    op.alter_column('crm_activities', 'followup_done',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('crm_activities', 'activity_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'call'::character varying"),
               existing_nullable=True)
    op.add_column('audit_logs', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('login_attempts_pkey'))
    )
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', [sa.literal_column('attempted_at DESC')], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_token_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoke_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey')),
    sa.UniqueConstraint('session_token_id', name=op.f('user_sessions_session_token_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['session_token_id'], unique=False)
    op.create_table('sourcing_deals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('deal_code', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('dealer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('gst_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('pickup_location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pickup_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('item_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lot_type', sa.VARCHAR(length=30), server_default=sa.text("'refurbishment'::character varying"), autoincrement=False, nullable=True),
    sa.Column('device_sale_mode', sa.VARCHAR(length=30), server_default=sa.text("'refurbished'::character varying"), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('estimated_buy_value', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('estimated_repair_cost', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('estimated_logistics_cost', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('target_sale_value', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('expected_margin', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('inspection_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('inspection_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('inspection_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pickup_alignment', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('packing_status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('po_requested', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('po_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('po_status', sa.VARCHAR(length=30), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=True),
    sa.Column('approval_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('approval_status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deal_status', sa.VARCHAR(length=30), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=True),
    sa.Column('lost_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_action_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('sourcing_deals_dealer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sourcing_deals_pkey')),
    sa.UniqueConstraint('deal_code', name=op.f('sourcing_deals_deal_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sourcing_deals_status'), 'sourcing_deals', ['deal_status', 'approval_status'], unique=False)
    op.create_index(op.f('ix_sourcing_deals_next_action'), 'sourcing_deals', ['next_action_date'], unique=False)
    op.create_index(op.f('ix_sourcing_deals_account_name'), 'sourcing_deals', ['account_name'], unique=False)
    op.drop_index(op.f('ix_crm_grade_price_matrix_device_type'), table_name='crm_grade_price_matrix')
    op.drop_table('crm_grade_price_matrix')
    # ### end Alembic commands ###
