"""add_qa_uat_tables

Revision ID: 0c716e3ade5c
Revises: ba22dd09a6a3
Create Date: 2026-04-01 13:04:07.059987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c716e3ade5c'
down_revision: Union[str, None] = 'ba22dd09a6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_qa', 'qa_done', 'in_uat', 'uat_done', 'approved', 'deployed', 'rolled_back', name='release_status_enum'), nullable=False),
    sa.Column('planned_date', sa.DateTime(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('qa_sign_off_by', sa.String(length=100), nullable=True),
    sa.Column('qa_sign_off_at', sa.DateTime(), nullable=True),
    sa.Column('uat_sign_off_by', sa.String(length=100), nullable=True),
    sa.Column('uat_sign_off_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('req_code', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('brd', 'prd', 'user_story', 'change_req', 'bug_fix', name='req_source_enum'), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='req_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'deferred', name='req_status_enum'), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tc_code', sa.String(length=30), nullable=True),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('functional', 'negative', 'boundary', 'integration', 'api', 'performance', 'regression', 'uat', name='tc_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'retired', name='tc_status_enum'), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['qa_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_uat_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uat_code', sa.String(length=30), nullable=True),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('business_owner', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'pass_', 'fail', 'blocked', name='uat_status_enum'), nullable=False),
    sa.Column('executed_by', sa.String(length=100), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('result_notes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('sign_off_by', sa.String(length=100), nullable=True),
    sa.Column('sign_off_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['qa_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_defects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('defect_code', sa.String(length=30), nullable=True),
    sa.Column('test_case_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='defect_severity_enum'), nullable=False),
    sa.Column('priority', sa.Enum('p1', 'p2', 'p3', 'p4', name='defect_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('new', 'assigned', 'in_progress', 'fixed', 'retest', 'closed', 'reopened', 'wont_fix', name='defect_status_enum'), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('build_version', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['qa_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_test_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pass_', 'fail', 'blocked', 'skipped', name='exec_status_enum'), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('build_version', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('executed_by', sa.String(length=100), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['qa_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('iqc_inspections', sa.Column('stress_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iqc_inspections', 'stress_report')
    op.drop_table('qa_test_executions')
    op.drop_table('qa_defects')
    op.drop_table('qa_uat_scenarios')
    op.drop_table('qa_test_cases')
    op.drop_table('qa_requirements')
    op.drop_table('qa_releases')
    # ### end Alembic commands ###
