"""
Gate Pass — security-gate view of sold devices ready to exit the premises.

The guard (or any role granted the gate_pass module in the Permission Matrix)
sees every sold tag number with its Delivery Challan, and can confirm the
physical exit. The DC itself is the existing /invoices/waybill/{sale_id}
document — generated by the system at the time of sale.

The tag-number table is server-side DataTables (see /gate-pass/data) rather
than a single query capped at 500 rows rendered into the page — the old cap
meant any sale beyond the most recent 500 was simply invisible here, same
class of problem fixed on the Sales list page.
"""
from html import escape

from templates_config import templates
from utils.timezone import app_now
from utils.date_filter import apply_date_range
from fastapi import APIRouter, Depends, Request, HTTPException, Query, Form
from fastapi.responses import HTMLResponse, RedirectResponse, JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc, asc, func, or_

from database import get_db
from models.user import User, UserRole
from models.device import Device
from models.lot import Lot
from models.sales import Sale, Return
from services.audit_engine import audit
from auth.dependencies import require_roles, verify_csrf

router = APIRouter(prefix="/gate-pass", tags=["gate-pass"],
                   dependencies=[Depends(verify_csrf)])
allowed = require_roles(UserRole.admin, UserRole.sales_manager, UserRole.sales,
                        UserRole.inventory_manager)


def _gate_pass_filters(sale_date_from, sale_date_to, lot_number):
    """Filter clauses shared by the page and its data endpoint, so the two
    can never disagree about what the filters mean."""
    w = []
    apply_date_range(w, Sale.sold_at, sale_date_from, sale_date_to)
    if lot_number:
        w.append(Lot.lot_number.ilike(f"%{lot_number}%"))
    return w


@router.get("", response_class=HTMLResponse)
@router.get("/", response_class=HTMLResponse)
async def gate_pass_list(request: Request,
                         sale_date_from: str = Query(default=""),
                         sale_date_to: str = Query(default=""),
                         lot_number: str = Query(default=""),
                         db: AsyncSession = Depends(get_db),
                         current_user: User = Depends(allowed)):
    # Rows are supplied by /gate-pass/data (server-side DataTables) — nothing
    # is queried/rendered here beyond the filter values themselves.
    return templates.TemplateResponse("gate_pass/list.html", {
        "request": request, "current_user": current_user,
        "sale_date_from": sale_date_from, "sale_date_to": sale_date_to,
        "lot_number": lot_number,
        "success": request.query_params.get("success"),
        "error": request.query_params.get("error"),
    })


# NOTE: /gate-pass/data MUST stay above any /gate-pass/{sale_id} route —
# FastAPI matches in registration order, and a parameterised route would
# otherwise capture "data" as a sale id and 404. (No such route exists today,
# but /gate-pass/{sale_id}/exit is prefix-based so this order is future-safe.)
@router.get("/data")
async def gate_pass_data(
    request: Request,
    draw: int = Query(default=1),
    start: int = Query(default=0),
    length: int = Query(default=25),
    sale_date_from: str = Query(default=""),
    sale_date_to: str = Query(default=""),
    lot_number: str = Query(default=""),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(allowed),
):
    """DataTables server-side feed for the Gate Pass tag-number table."""
    base_join = (
        select(Sale, Device.id, Device.barcode, Device.brand, Device.model, Lot.lot_number)
        .join(Device, Sale.device_id == Device.id)
        .outerjoin(Lot, Device.lot_id == Lot.id)
    )
    count_join = (
        select(func.count())
        .select_from(Sale)
        .join(Device, Sale.device_id == Device.id)
        .outerjoin(Lot, Device.lot_id == Lot.id)
    )

    page_filters = _gate_pass_filters(sale_date_from, sale_date_to, lot_number)

    search = (request.query_params.get("search[value]") or "").strip()
    search_filters = []
    if search:
        like = f"%{search}%"
        search_filters.append(or_(
            Device.barcode.ilike(like), Device.brand.ilike(like),
            Device.model.ilike(like), Sale.sale_number.ilike(like),
            Sale.customer_name.ilike(like), Lot.lot_number.ilike(like),
        ))

    total = (await db.execute(count_join.where(*page_filters))).scalar() or 0
    filtered = (await db.execute(
        count_join.where(*page_filters, *search_filters))).scalar() or 0

    # Column indices match templates/gate_pass/list.html's <thead>: 0=checkbox,
    # 1=Tag Number, 2=Lot, 3=Device, 4=Sale No, 5=Customer, 6=Sold At, ...
    col_map = {4: Sale.sale_number, 5: Sale.customer_name, 6: Sale.sold_at}
    try:
        order_col = int(request.query_params.get("order[0][column]", 6))
    except ValueError:
        order_col = 6
    order_dir = request.query_params.get("order[0][dir]", "desc")
    sort_expr = col_map.get(order_col, Sale.sold_at)
    order_by = asc(sort_expr) if order_dir == "asc" else desc(sort_expr)

    rows = (await db.execute(
        base_join.where(*page_filters, *search_filters)
        .order_by(order_by, Sale.sale_number)   # tie-break, so paging is stable
        .offset(max(0, start)).limit(min(max(1, length), 500))
    )).all()

    def esc(v):
        return escape(str(v)) if v is not None else ""

    # "Customer Return" label under Tag Number (Return Stock's Complete
    # action) — a device carries this label forever once it has ANY Return
    # row, regardless of Device.return_status (which flips back to False the
    # moment Complete re-sells it), so the badge survives past that reset.
    device_ids_on_page = [device_id for _sale, device_id, *_rest in rows]
    returned_device_ids = set()
    if device_ids_on_page:
        returned_device_ids = set((await db.execute(
            select(Return.device_id).where(Return.device_id.in_(device_ids_on_page)).distinct()
        )).scalars().all())

    data = []
    for sale, device_id, barcode, brand, model, lot_number_val in rows:
        tag_html = f'<code>{esc(barcode)}</code>'
        if device_id in returned_device_ids:
            tag_html += '<br><span class="badge bg-info text-dark">Customer Return</span>'

        if sale.delivery_status == "delivered":
            status_html = '<span class="badge bg-success">Delivered</span>'
        elif sale.delivery_status == "dispatched":
            status_html = '<span class="badge bg-info text-dark">Dispatched</span>'
        else:
            status_html = '<span class="badge bg-warning text-dark">Ready to Exit</span>'

        can_exit = sale.delivery_status not in ("dispatched", "delivered")
        action_html = (
            f'<button type="button" class="btn btn-sm btn-success py-0 px-2 gp-exit-one" '
            f'data-id="{sale.id}" data-barcode="{esc(barcode)}">'
            f'<i class="bi bi-box-arrow-right me-1"></i>Confirm Exit</button>'
            if can_exit else '<span class="text-muted small">—</span>'
        )
        checkbox_html = (
            f'<input type="checkbox" class="row-check" value="{sale.id}">' if can_exit
            else '<input type="checkbox" class="row-check" value="" disabled>'
        )

        data.append([
            checkbox_html,
            tag_html,
            f'<span class="font-monospace">{esc(lot_number_val) or "—"}</span>',
            esc(f"{brand or ''} {model or ''}".strip()) or "—",
            f'<span class="font-monospace">{esc(sale.sale_number)}</span>',
            esc(sale.customer_name or "—"),
            sale.sold_at.strftime("%d-%b-%Y %H:%M") if sale.sold_at else "—",
            status_html,
            f'<a href="/invoices/waybill/{sale.id}" target="_blank" '
            f'class="btn btn-sm btn-outline-primary py-0 px-2">'
            f'<i class="bi bi-file-earmark-text me-1"></i>DC</a>',
            action_html,
        ])

    return JSONResponse({
        "draw": draw, "recordsTotal": total, "recordsFiltered": filtered, "data": data,
    })


@router.post("/{sale_id}/exit")
async def confirm_exit(sale_id: str, request: Request,
                       db: AsyncSession = Depends(get_db),
                       current_user: User = Depends(allowed)):
    """Guard confirms the goods physically left the gate."""
    import uuid as _u
    try:
        sid = _u.UUID(sale_id)
    except ValueError:
        raise HTTPException(404)
    sale = (await db.execute(select(Sale).where(Sale.id == sid))).scalar_one_or_none()
    if not sale:
        raise HTTPException(404, "Sale not found")
    sale.delivery_status = "dispatched"
    if not sale.dispatch_date:
        sale.dispatch_date = app_now()
    await audit(db, user=current_user, action="GATE_EXIT_CONFIRMED",
                table_name="sales", record_id=str(sale.id),
                new_value={"sale_number": sale.sale_number}, request=request)
    await db.commit()
    return RedirectResponse(url="/gate-pass?success=Exit+confirmed", status_code=302)


@router.post("/bulk-exit")
async def bulk_confirm_exit(request: Request,
                            sale_ids: str = Form(""),
                            db: AsyncSession = Depends(get_db),
                            current_user: User = Depends(allowed)):
    """Confirm exit for every checked row in one call. Sales already
    dispatched/delivered are silently skipped rather than erroring the whole
    batch — a guard selecting a mixed page shouldn't have to re-pick."""
    import uuid as _u
    ids = []
    for raw in sale_ids.split(","):
        raw = raw.strip()
        if not raw:
            continue
        try:
            ids.append(_u.UUID(raw))
        except ValueError:
            continue
    if not ids:
        return RedirectResponse(url="/gate-pass?error=No+tags+selected", status_code=302)

    sales = (await db.execute(select(Sale).where(Sale.id.in_(ids)))).scalars().all()
    confirmed, skipped = 0, 0
    stamp = app_now()
    for sale in sales:
        if sale.delivery_status in ("dispatched", "delivered"):
            skipped += 1
            continue
        sale.delivery_status = "dispatched"
        if not sale.dispatch_date:
            sale.dispatch_date = stamp
        confirmed += 1

    if confirmed:
        await audit(db, user=current_user, action="GATE_EXIT_BULK_CONFIRMED",
                    table_name="sales", record_id=None,
                    new_value={"confirmed": confirmed, "skipped": skipped},
                    request=request)
        await db.commit()

    msg = f"{confirmed} tag(s) confirmed exited"
    if skipped:
        msg += f" — {skipped} already exited, skipped"
    return RedirectResponse(url=f"/gate-pass?success={msg}", status_code=302)
