"""
Gate Pass — security-gate view of sold devices ready to exit the premises.

The guard (or any role granted the gate_pass module in the Permission Matrix)
sees every sold tag number with its Delivery Challan, and can confirm the
physical exit. The DC itself is the existing /invoices/waybill/{sale_id}
document — generated by the system at the time of sale.
"""
from templates_config import templates
from utils.timezone import app_now
from fastapi import APIRouter, Depends, Request, HTTPException
from fastapi.responses import HTMLResponse, RedirectResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc

from database import get_db
from models.user import User, UserRole
from models.device import Device
from models.lot import Lot
from models.sales import Sale
from services.audit_engine import audit
from auth.dependencies import require_roles, verify_csrf

router = APIRouter(prefix="/gate-pass", tags=["gate-pass"],
                   dependencies=[Depends(verify_csrf)])
allowed = require_roles(UserRole.admin, UserRole.sales_manager, UserRole.sales,
                        UserRole.inventory_manager)


@router.get("", response_class=HTMLResponse)
@router.get("/", response_class=HTMLResponse)
async def gate_pass_list(request: Request,
                         db: AsyncSession = Depends(get_db),
                         current_user: User = Depends(allowed)):
    rows = (await db.execute(
        select(Sale, Device.barcode, Device.brand, Device.model, Lot.lot_number)
        .join(Device, Sale.device_id == Device.id)
        .outerjoin(Lot, Device.lot_id == Lot.id)
        .order_by(desc(Sale.sold_at))
        .limit(500)
    )).all()
    return templates.TemplateResponse("gate_pass/list.html", {
        "request": request, "current_user": current_user, "rows": rows,
    })


@router.post("/{sale_id}/exit")
async def confirm_exit(sale_id: str, request: Request,
                       db: AsyncSession = Depends(get_db),
                       current_user: User = Depends(allowed)):
    """Guard confirms the goods physically left the gate."""
    import uuid as _u
    try:
        sid = _u.UUID(sale_id)
    except ValueError:
        raise HTTPException(404)
    sale = (await db.execute(select(Sale).where(Sale.id == sid))).scalar_one_or_none()
    if not sale:
        raise HTTPException(404, "Sale not found")
    sale.delivery_status = "dispatched"
    if not sale.dispatch_date:
        sale.dispatch_date = app_now()
    await audit(db, user=current_user, action="GATE_EXIT_CONFIRMED",
                table_name="sales", record_id=str(sale.id),
                new_value={"sale_number": sale.sale_number}, request=request)
    await db.commit()
    return RedirectResponse(url="/gate-pass?success=Exit+confirmed", status_code=302)
