import uuid
from utils.timezone import app_now
from sqlalchemy import Column, String, DateTime, Numeric, ForeignKey, Boolean, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from database import Base


class ScrapForSale(Base):
    """One row per Scrap for Sale batch, created from /transfers when
    Transfer Type = Scrap for Sale. Its Tag Numbers / Spare Parts are the
    StockTransfer rows that reference it (StockTransfer.scrap_for_sale_id),
    same "the transfer log is the membership list" pattern buckets/lots use."""
    __tablename__ = "scrap_for_sale"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    scrap_id = Column(String(4), unique=True, nullable=False, index=True)  # autogenerated, e.g. "0001"
    assigned_to_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    min_selling_price = Column(Numeric(12, 2), nullable=True)
    max_selling_price = Column(Numeric(12, 2), nullable=True)
    status = Column(String(20), nullable=False, default="open")  # open | sold
    is_trashed = Column(Boolean, nullable=False, default=False, server_default=text("false"))
    created_by = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=app_now)

    assigned_to = relationship("User", lazy="select")
    transfers = relationship("StockTransfer", back_populates="scrap_for_sale", lazy="select")
